### ISSUE TITLE
Spring Security 5.8.8 에서 requestMatchers() 설정을 하면 서버 시작 예외가 발생함

### ISSUE THREAD

**Issue by fp024** [fp024/spring-5-recipes-study#14]
## 문제

Spring Security 5.8.8 에서 requestMatchers() 설정을 하면 다음과 같은 서버 시작 예외가 발생함

### 관련된 예제 루트
* https://github.com/fp024/spring-5-recipes-study/tree/master/chap07/recipe-7-01-iii

### 예외 로그
```
Caused by: java.lang.UnsupportedOperationException: Servlet 3.0 스펙의 4.4 장에 따르면, web.xml 또는 web-fragment.xml 파일에 정의되지 않거나 @WebListener로 annotate되지 않은, ServletContextListener에서 이 메소드를 호출하는 것은 허용되지 않습니다.
	at org.apache.catalina.core.StandardContext$NoPluggabilityServletContext.getServletRegistrations(StandardContext.java:6306) ~[catalina.jar:9.0.80]
	at org.springframework.security.config.annotation.web.AbstractRequestMatcherRegistry.mappableServletRegistrations(AbstractRequestMatcherRegistry.java:333) ~[spring-security-config-5.8.8.jar:5.8.8]
	at org.springframework.security.config.annotation.web.AbstractRequestMatcherRegistry.requestMatchers(AbstractRequestMatcherRegistry.java:317) ~[spring-security-config-5.8.8.jar:5.8.8]
	at org.springframework.security.config.annotation.web.AbstractRequestMatcherRegistry.requestMatchers(AbstractRequestMatcherRegistry.java:394) ~[spring-security-config-5.8.8.jar:5.8.8]
	at org.fp024.study.spring5recipes.board.security.TodoSecurityConfig.lambda$securityFilterChain$0(TodoSecurityConfig.java:57) ~[classes/:?]
```

### 오류가 발생하는 설정
```java
    http.authorizeHttpRequests(
        (authz) ->
            authz
                .requestMatchers(
                    "/webjars/**", //
                    "/resources/**",
                    "/",
                    "/index",
                    "/favicon.ico")
                .permitAll()
                .requestMatchers(HttpMethod.DELETE, "/todos/*")
                .hasAuthority("ADMIN")
                .anyRequest()
                .authenticated());
```

#### 1. antMatcher()를 사용한다.
```java
      http.authorizeHttpRequests(
        (authz) ->
            authz
                .requestMatchers(
                    antMatcher("/webjars/**"), //
                    antMatcher("/resources/**"), //
                    antMatcher("/"),
                    antMatcher("/index"),
                    antMatcher("/favicon.ico"))
                .permitAll()
                .requestMatchers(antMatcher(HttpMethod.DELETE, "/todos/*"))
                .hasAuthority("ADMIN")
                .anyRequest()
                .authenticated());
```

#### 2. 설정을 그대로 유지하고 Spring Security 버전을 5.8.4로 낮춘다.

그런데 나의 예제 환경의 경우에는 다음 Bean을 보안 설정 클래스에 넣어줘야함.
```java
  @Bean
  HandlerMappingIntrospector mvcHandlerMappingIntrospector() {
    return new HandlerMappingIntrospector();
  }
```

### 이슈 검색
- 동일한 문제로 Github에 이슈가 등록되어있음.
  * `https://github.com/spring-projects/spring-security/issues/13789`
  * `https://github.com/spring-projects/spring-security/issues/13794`

## 해결

- [x] 아직은 antMatcher로 사용하고 있다가 Spring Seucirty Github에 올라온 이슈 해결되면 참고해서 바꾸도록 하자. 😅

**Comment by fp024** [comment]
나중에 신버전 나오면 그냥  `.requestMatchers(...)` 만 써서도 잘되도록 변경이 될지는 모르겠는데...  그 때 다시 확인해보면 되겠다.  이슈는 닫자 😅

**Comment by fp024** [comment]
Spring Security 5.8.9-SNAPSHOT에서 확인해봤는데... 그냥 requestMatchers()만 사용해서도 잘되는 것을 확인했다.

* 389dc28350912ceaaf36be87b13007f635bffa67

그런데...

* https://github.com/spring-projects/spring-security/blob/main/docs/modules/ROOT/pages/servlet/configuration/java.adoc#configuring-for-multiple-spring-mvc-dispatchers

나의 경우는 이렇게 사용하면 반드시 다음 예외가 발생하는데..
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'springSecurityFilterChain' available
```

루트 설정에 설정 클래스가 지정되어있으면, Spring Security 설정 클래스가 거기에 포함이 되어야 저런 오류가 생기지 않음.

그래서 일단 ROOT, Web, Security 설정을 getServletConfigClasses()에다 넣어봤는데... 이때는 잘됨.

그런데 여기다 3개 설정을 전부 몰아두는 것도 좀 이상한 것 같기도 하고...😅
